yarnPath: .yarn/releases/yarn-3.6.4.cjs
nodeLinker: node-modules
packageExtensions:
  ember-assign-polyfill@*:
    dependencies:
      "@babel/core": "*"
      "webpack": "*"
  ember-cli-babel@*:
    dependencies:
      "@babel/core": "*"
  ember-cli-typescript@*:
    dependencies:
      "@babel/core": "*"
  ember-compatibility-helpers@*:
    dependencies:
      "@babel/core": "*"
  ember-auto-import@*:
    dependencies:
      "webpack": "*"
